# Google Maven
# https://maven.google.com/web/index.html?hl=zh-cn

# Gradle Plugins
# https://plugins.gradle.org/

# Maven
# https://mvnrepository.com/

[versions]
agp = "8.0.2"
kotlin = "1.8.21"
compose-compiler = "1.4.7"
compose = "1.4.3"
room = "2.5.1"
ktx-serialization = "1.5.1"
accompanist = "0.30.1"
rikka-shizuku = "13.1.1"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.1" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.0" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.5.3" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.4.3" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version = "2.8.1" }

# Kotlin Serialization
# https://github.com/Kotlin/kotlinx.serialization/blob/master/README.md#setup
# https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md
ktx-serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktx-serialization" }

# AndroidHiddenApiBypass
# https://github.com/LSPosed/AndroidHiddenApiBypass
lsposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "4.3" }

# Koin Inject
# https://insert-koin.io/docs/setup/koin
koin-core = { group = "io.insert-koin", name = "koin-core", version = "3.4.0" }
koin-android = { group = "io.insert-koin", name = "koin-android", version = "3.4.0" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version = "3.4.4" }

# Lottie for Android Compose
# http://airbnb.io/lottie/#/android-compose
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version = "6.0.0" }

# Pager layouts
# https://google.github.io/accompanist/pager/
accompanist-navigationAnimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

# Rikka Shizuku
# https://github.com/RikkaApps/Shizuku-API
rikka-shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "rikka-shizuku" }
rikka-shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "rikka-shizuku" }

# Coil: An image loader for Compose
# https://coil-kt.github.io/coil/compose/
compose-coil = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }

# XXPermissions
# https://github.com/getActivity/XXPermissions
xxpermissions = { group = "com.github.getActivity", name = "XXPermissions", version = "16.6" }

# Dhizuku-API
# https://github.com/iamr0s/Dhizuku-API
iamr0s-dhizuku-api = { group = "io.github.iamr0s", name = "Dhizuku-API", version = "2.3" }

# AndroidAppProcess
# https://github.com/iamr0s/AndroidAppProcess
iamr0s-androidAppProcess = { group = "io.github.iamr0s", name = "AndroidAppProcess", version = "1.2" }
